language: python
python:
    - "2.7"

branches:
    only:
        - master

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get -y --force-yes install python-libvirt python-lzma python-yaml

install:
    - pip install -r requirements-travis.txt

script:
    - inspekt lint
    - inspekt indent
    - inspekt style
    - ./selftests/run selftests/all/doc
    - ./selftests/run selftests/all/functional
    - ./selftests/run selftests/all/unit
